version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway/backend
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - dd-user
      - dd-ctf
      - dd-blog
      - dd-task-tracker

  dd-user:
    build:
      context: ./services/dd-user/backend
      dockerfile: Dockerfile
    container_name: dd-user
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@user-db:5432/cslp_user
    depends_on:
      - user-db
      - dd-user-migrations

  dd-ctf:
    build:
      context: ./services/dd-ctf/backend
      dockerfile: Dockerfile
    container_name: dd-ctf
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ctf-db:5432/cslp_ctf
    depends_on:
      - ctf-db
      - dd-ctf-migrations

  dd-blog:
    build:
      context: ./services/dd-blog/backend
      dockerfile: Dockerfile
    container_name: dd-blog
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@blog-db:5432/cslp_blog
    depends_on:
      - blog-db
      - dd-blog-migrations

  dd-task-tracker:
    build:
      context: ./services/dd-task-tracker/backend
      dockerfile: Dockerfile
    container_name: dd-task-tracker
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@task-tracker-db:5432/cslp_task_tracker
    depends_on:
      - task-tracker-db
      - dd-task-tracker-migrations

  dd-user-migrations:
    build:
      context: ./services/dd-user/backend
      dockerfile: Dockerfile.migrations
    container_name: dd-user-migrations
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@user-db:5432/cslp_user
    depends_on:
      - user-db

  dd-ctf-migrations:
    build:
      context: ./services/dd-ctf/backend
      dockerfile: Dockerfile.migrations
    container_name: dd-ctf-migrations
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ctf-db:5432/cslp_ctf
    depends_on:
      - ctf-db

  dd-blog-migrations:
    build:
      context: ./services/dd-blog/backend
      dockerfile: Dockerfile.migrations
    container_name: dd-blog-migrations
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@blog-db:5432/cslp_blog
    depends_on:
      - blog-db

  dd-task-tracker-migrations:
    build:
      context: ./services/dd-task-tracker/backend
      dockerfile: Dockerfile.migrations
    container_name: dd-task-tracker-migrations
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@task-tracker-db:5432/cslp_task_tracker
    depends_on:
      - task-tracker-db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    volumes:
      - user-db-data:/var/lib/postgresql/data

  ctf-db:
    image: postgres:16
    container_name: ctf-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ctf_db
    volumes:
      - ctf-db-data:/var/lib/postgresql/data

  blog-db:
    image: postgres:16
    container_name: blog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog_db
    volumes:
      - blog-db-data:/var/lib/postgresql/data

  task-tracker-db:
    image: postgres:16
    container_name: task-tracker-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_tracker_db
    volumes:
      - task-tracker-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
  ctf-db-data:
  blog-db-data:
  task-tracker-db-data:
