@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class alembic_version {
   version_num: varchar(32)
}
class blocked_ips {
   ip_address: varchar
   block_reason: varchar
   blocked_at: timestamp
   created_at: timestamp
   id: bigint
}
class login_attempts {
   user_id: bigint
   attempt_time: timestamp
   ip_address_v4: varchar
   ip_address_v6: varchar
   user_agent: varchar
   successful: boolean
   created_at: timestamp
   id: bigint
}
class password_changes {
   user_id: bigint
   old_password_hash: bytea
   new_password_hash: bytea
   change_time: timestamp
   created_at: timestamp
   id: bigint
}
class permissions {
   name: varchar
   description: varchar
   created_at: timestamp
   id: bigint
}
class role_permission_association {
   role_id: bigint
   permission_id: bigint
}
class roles {
   name: varchar
   description: varchar
   created_at: timestamp
   id: bigint
}
class user_access_log {
   user_id: bigint
   timestamp: timestamp
   ip_address: varchar
   action: varchar
   status: varchar
   user_agent: varchar
   location: varchar
   created_at: timestamp
   id: bigint
}
class user_permission_association {
   user_id: bigint
   permission_id: bigint
}
class user_role_association {
   user_id: bigint
   role_id: bigint
}
class user_security {
   user_id: bigint
   last_login: timestamp
   login_attempts: integer
   last_failed_login: timestamp
   password_changed_at: timestamp
   password_reset_token: varchar
   password_reset_token_expires_at: timestamp
   account_lock: boolean
   account_lock_until: timestamp
   created_at: timestamp
   id: bigint
}
class user_sessions {
   user_id: bigint
   session_token: varchar
   created_at: timestamp
   expires_at: timestamp
   ip_address: varchar
   user_agent: varchar
   id: bigint
}
class user_settings {
   user_id: bigint
   setting_name: varchar
   setting_value: varchar
   last_updated: timestamp
   created_at: timestamp
   id: bigint
}
class users {
   username: varchar
   password_hash: bytea
   email: varchar
   phone_number: varchar
   full_name: varchar
   is_admin: boolean
   is_active: boolean
   created_at: timestamp
   updated_at: timestamp
   id: bigint
}

login_attempts               -[#595959,plain]-^  users                       : "user_id:id"
password_changes             -[#595959,plain]-^  users                       : "user_id:id"
role_permission_association  -[#595959,plain]-^  permissions                 : "permission_id:id"
role_permission_association  -[#595959,plain]-^  roles                       : "role_id:id"
user_access_log              -[#595959,plain]-^  users                       : "user_id:id"
user_permission_association  -[#595959,plain]-^  permissions                 : "permission_id:id"
user_permission_association  -[#595959,plain]-^  users                       : "user_id:id"
user_role_association        -[#595959,plain]-^  roles                       : "role_id:id"
user_role_association        -[#595959,plain]-^  users                       : "user_id:id"
user_security                -[#595959,plain]-^  users                       : "user_id:id"
user_sessions                -[#595959,plain]-^  users                       : "user_id:id"
user_settings                -[#595959,plain]-^  users                       : "user_id:id"
@enduml
